# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # API stateless : pas de session côté serveur.
    session: false

    http_method_override: false
    handle_all_throwables: true

when@test:
    framework:
        test: true
