<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Post-MVP vague 2 — PMVP-004 : table `habits` (CRUD habitudes utilisateur).
 *
 * - FK `user_id` non-nullable (chaque habitude appartient à un user).
 * - FK `category_id` nullable + ON DELETE SET NULL : la suppression d'une
 *   catégorie ne casse pas les habitudes existantes (cf. PMVP-001).
 * - Récompenses XP/Gold avec CHECK >= 0.
 */
final class Version20260528180100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Post-MVP PMVP-004 : table habits (habitudes utilisateur).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE habits (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                category_id INT DEFAULT NULL,
                name VARCHAR(100) NOT NULL,
                description TEXT NOT NULL,
                xp_reward INT NOT NULL DEFAULT 0,
                gold_reward INT NOT NULL DEFAULT 0,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE INDEX idx_habits_user ON habits (user_id)');
        $this->addSql('CREATE INDEX idx_habits_category ON habits (category_id)');

        $this->addSql(<<<'SQL'
            ALTER TABLE habits
            ADD CONSTRAINT fk_habits_user
            FOREIGN KEY (user_id)
            REFERENCES users (id)
            NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE habits
            ADD CONSTRAINT fk_habits_category
            FOREIGN KEY (category_id)
            REFERENCES categories (id)
            ON DELETE SET NULL
            NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE habits
            ADD CONSTRAINT chk_habits_xp_reward_positive
            CHECK (xp_reward >= 0)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE habits
            ADD CONSTRAINT chk_habits_gold_reward_positive
            CHECK (gold_reward >= 0)
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS habits');
    }
}
