<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Post-MVP vague 3 — PMVP-014 : table `inventories` (inventaire utilisateur).
 *
 * - FK `user_id` non-nullable, ON DELETE CASCADE : la suppression d'un user
 *   purge automatiquement son inventaire.
 * - FK `item_id` non-nullable, ON DELETE RESTRICT : on refuse explicitement
 *   la suppression d'un item du catalogue tant qu'au moins un user en
 *   possède un exemplaire (sécurité référentielle ; un admin devra purger
 *   les exemplaires avant de supprimer un item).
 * - Plusieurs lignes pour le couple `(user_id, item_id)` sont autorisées :
 *   inventaire à exemplaires, pas collection unique. Aucune contrainte
 *   d'unicité sur ce couple.
 * - `is_equipped` défaut FALSE : l'équipement (PMVP-015) est hors-scope ici.
 */
final class Version20260528190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Post-MVP PMVP-014 : table inventories (inventaire utilisateur).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE inventories (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                item_id INT NOT NULL,
                acquired_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                is_equipped BOOLEAN NOT NULL DEFAULT FALSE,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE INDEX idx_inventories_user ON inventories (user_id)');
        $this->addSql('CREATE INDEX idx_inventories_item ON inventories (item_id)');

        $this->addSql(<<<'SQL'
            ALTER TABLE inventories
            ADD CONSTRAINT fk_inventories_user
            FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
            NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE inventories
            ADD CONSTRAINT fk_inventories_item
            FOREIGN KEY (item_id)
            REFERENCES items (id)
            ON DELETE RESTRICT
            NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS inventories');
    }
}
