<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420174225 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event_quest_selections (event_id INT NOT NULL, quest_template_id INT NOT NULL, PRIMARY KEY (event_id, quest_template_id))');
        $this->addSql('CREATE INDEX IDX_AD91C95371F7E88B ON event_quest_selections (event_id)');
        $this->addSql('CREATE INDEX IDX_AD91C953328A9A4F ON event_quest_selections (quest_template_id)');
        $this->addSql('CREATE TABLE events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5387574A7D182D95 ON events (created_by_user_id)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('CREATE TABLE quest_templates (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kind VARCHAR(20) NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, is_active BOOLEAN NOT NULL, xp_reward INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_quest_action_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment TEXT NOT NULL, action_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, user_quest_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4921538EA76ED395 ON user_quest_action_logs (user_id)');
        $this->addSql('CREATE INDEX IDX_4921538EC0137AF4 ON user_quest_action_logs (user_quest_id)');
        $this->addSql('CREATE TABLE user_quests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, is_validated BOOLEAN NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, quest_template_id INT NOT NULL, event_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FDCC4609A76ED395 ON user_quests (user_id)');
        $this->addSql('CREATE INDEX IDX_FDCC4609328A9A4F ON user_quests (quest_template_id)');
        $this->addSql('CREATE INDEX IDX_FDCC460971F7E88B ON user_quests (event_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, xp INT NOT NULL, role VARCHAR(10) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('ALTER TABLE event_quest_selections ADD CONSTRAINT FK_AD91C95371F7E88B FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_quest_selections ADD CONSTRAINT FK_AD91C953328A9A4F FOREIGN KEY (quest_template_id) REFERENCES quest_templates (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574A7D182D95 FOREIGN KEY (created_by_user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_quest_action_logs ADD CONSTRAINT FK_4921538EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_quest_action_logs ADD CONSTRAINT FK_4921538EC0137AF4 FOREIGN KEY (user_quest_id) REFERENCES user_quests (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_quests ADD CONSTRAINT FK_FDCC4609A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_quests ADD CONSTRAINT FK_FDCC4609328A9A4F FOREIGN KEY (quest_template_id) REFERENCES quest_templates (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_quests ADD CONSTRAINT FK_FDCC460971F7E88B FOREIGN KEY (event_id) REFERENCES events (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event_quest_selections DROP CONSTRAINT FK_AD91C95371F7E88B');
        $this->addSql('ALTER TABLE event_quest_selections DROP CONSTRAINT FK_AD91C953328A9A4F');
        $this->addSql('ALTER TABLE events DROP CONSTRAINT FK_5387574A7D182D95');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE user_quest_action_logs DROP CONSTRAINT FK_4921538EA76ED395');
        $this->addSql('ALTER TABLE user_quest_action_logs DROP CONSTRAINT FK_4921538EC0137AF4');
        $this->addSql('ALTER TABLE user_quests DROP CONSTRAINT FK_FDCC4609A76ED395');
        $this->addSql('ALTER TABLE user_quests DROP CONSTRAINT FK_FDCC4609328A9A4F');
        $this->addSql('ALTER TABLE user_quests DROP CONSTRAINT FK_FDCC460971F7E88B');
        $this->addSql('DROP TABLE event_quest_selections');
        $this->addSql('DROP TABLE events');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE quest_templates');
        $this->addSql('DROP TABLE user_quest_action_logs');
        $this->addSql('DROP TABLE user_quests');
        $this->addSql('DROP TABLE users');
    }
}
