<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Post-MVP PMVP-028 — journal d'audit des actions admin.
 */
final class Version20260528270000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Post-MVP PMVP-028 : table admin_audit_log.';
    }

    public function up(Schema $schema): void
    {
        if ($schema->hasTable('admin_audit_log')) {
            return;
        }

        $this->addSql(<<<'SQL'
            CREATE TABLE admin_audit_log (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                admin_user_id INT NOT NULL,
                action VARCHAR(64) NOT NULL,
                target VARCHAR(255) NOT NULL,
                payload JSONB NOT NULL DEFAULT '{}',
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_admin_audit_log_admin ON admin_audit_log (admin_user_id)');
        $this->addSql('CREATE INDEX idx_admin_audit_log_created ON admin_audit_log (created_at)');
        $this->addSql(<<<'SQL'
            ALTER TABLE admin_audit_log
                ADD CONSTRAINT FK_admin_audit_log_admin_user
                FOREIGN KEY (admin_user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE admin_audit_log DROP CONSTRAINT IF EXISTS FK_admin_audit_log_admin_user');
        $this->addSql('DROP TABLE IF EXISTS admin_audit_log');
    }
}
