<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Post-MVP PMVP-020 + PMVP-021 — quest_conditions et quest_rewards.
 */
final class Version20260528220000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Post-MVP PMVP-020/021 : tables quest_conditions et quest_rewards.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE quest_conditions (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                quest_template_id INT NOT NULL,
                kind VARCHAR(40) NOT NULL,
                params JSON NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE INDEX idx_quest_conditions_template ON quest_conditions (quest_template_id)');

        $this->addSql(<<<'SQL'
            ALTER TABLE quest_conditions
            ADD CONSTRAINT fk_quest_conditions_template
            FOREIGN KEY (quest_template_id)
            REFERENCES quest_templates (id)
            ON DELETE CASCADE
            NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE quest_rewards (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                quest_template_id INT NOT NULL,
                xp INT NOT NULL,
                gold INT NOT NULL,
                item_id INT DEFAULT NULL,
                params JSON DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE UNIQUE INDEX uniq_quest_rewards_template ON quest_rewards (quest_template_id)');

        $this->addSql(<<<'SQL'
            ALTER TABLE quest_rewards
            ADD CONSTRAINT chk_quest_rewards_xp_non_negative
            CHECK (xp >= 0)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE quest_rewards
            ADD CONSTRAINT chk_quest_rewards_gold_non_negative
            CHECK (gold >= 0)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE quest_rewards
            ADD CONSTRAINT fk_quest_rewards_template
            FOREIGN KEY (quest_template_id)
            REFERENCES quest_templates (id)
            ON DELETE CASCADE
            NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE quest_rewards
            ADD CONSTRAINT fk_quest_rewards_item
            FOREIGN KEY (item_id)
            REFERENCES items (id)
            ON DELETE SET NULL
            NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS quest_rewards');
        $this->addSql('DROP TABLE IF EXISTS quest_conditions');
    }
}
