<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260529030000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Boutique : achats du jour persistés ; achievements alignés V2 (quêtes).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE shop_purchases (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                item_id INT NOT NULL,
                rotation_date VARCHAR(10) NOT NULL,
                purchased_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_shop_purchases_user_date ON shop_purchases (user_id, rotation_date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_shop_purchase_user_item_date ON shop_purchases (user_id, item_id, rotation_date)');
        $this->addSql(<<<'SQL'
            ALTER TABLE shop_purchases
            ADD CONSTRAINT fk_shop_purchases_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE shop_purchases
            ADD CONSTRAINT fk_shop_purchases_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);

        $this->addSql(<<<'SQL'
            UPDATE achievements
            SET code = 'first_quest_validated',
                name = 'Première quête',
                description = 'Valider votre première quête.'
            WHERE code = 'first_habit_log'
        SQL);
        $this->addSql(<<<'SQL'
            UPDATE achievements
            SET name = 'Discipline de fer',
                description = 'Valider 7 quêtes au total.'
            WHERE code = 'iron_discipline'
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE shop_purchases');
        $this->addSql(<<<'SQL'
            UPDATE achievements
            SET code = 'first_habit_log',
                name = 'Premier Pas',
                description = 'Enregistrer votre première exécution d''habitude.'
            WHERE code = 'first_quest_validated'
        SQL);
        $this->addSql(<<<'SQL'
            UPDATE achievements
            SET name = 'Discipline de Fer',
                description = 'Enregistrer 7 exécutions sur la même habitude.'
            WHERE code = 'iron_discipline'
        SQL);
    }
}
