<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * V2.2 — Séquence prédéfinie des boss (respawn ordonné).
 */
final class Version20260529021000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'V2.2 : table monster_sequence_steps pour la chaîne de boss.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE monster_sequence_steps (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                step_order INT NOT NULL,
                monster_template_id INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_monster_sequence_step_order ON monster_sequence_steps (step_order)');
        $this->addSql(<<<'SQL'
            ALTER TABLE monster_sequence_steps
            ADD CONSTRAINT fk_monster_sequence_step_template
            FOREIGN KEY (monster_template_id)
            REFERENCES monster_templates (id)
            ON DELETE CASCADE
            NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO monster_sequence_steps (step_order, monster_template_id)
            SELECT ROW_NUMBER() OVER (ORDER BY mt.id), mt.id
            FROM monster_templates mt
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS monster_sequence_steps');
    }
}
