<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Post-MVP PMVP-007 + PMVP-008 — monster_templates et user_monsters.
 */
final class Version20260528210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Post-MVP PMVP-007/008 : tables monster_templates et user_monsters.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE monster_templates (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(255) NOT NULL,
                base_hp INT NOT NULL,
                level_min INT NOT NULL,
                level_max INT NOT NULL,
                rarity VARCHAR(20) NOT NULL,
                affinity_stat VARCHAR(20) NOT NULL,
                loot_table JSON NOT NULL,
                image_url VARCHAR(500) DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE monster_templates
            ADD CONSTRAINT chk_monster_templates_base_hp_positive
            CHECK (base_hp > 0)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE monster_templates
            ADD CONSTRAINT chk_monster_templates_level_range
            CHECK (level_min <= level_max AND level_min >= 1)
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE user_monsters (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                template_id INT NOT NULL,
                current_hp INT NOT NULL,
                max_hp INT NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT true,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE INDEX idx_user_monsters_user ON user_monsters (user_id)');

        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_user_monsters_one_active_per_user
            ON user_monsters (user_id)
            WHERE is_active = true
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE user_monsters
            ADD CONSTRAINT chk_user_monsters_hp_non_negative
            CHECK (current_hp >= 0 AND max_hp > 0)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE user_monsters
            ADD CONSTRAINT fk_user_monsters_user
            FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
            NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE user_monsters
            ADD CONSTRAINT fk_user_monsters_template
            FOREIGN KEY (template_id)
            REFERENCES monster_templates (id)
            ON DELETE RESTRICT
            NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS user_monsters');
        $this->addSql('DROP TABLE IF EXISTS monster_templates');
    }
}
