<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Post-MVP vague 3 — PMVP-005 : table `habit_logs` (trace immuable des
 * exécutions d'habitudes).
 *
 * - FK `habit_id` non-nullable, ON DELETE CASCADE : si une habitude est
 *   supprimée par son user (PMVP-004), ses logs disparaissent — on n'a pas
 *   besoin de conserver l'historique d'une habitude effacée en V1.
 * - FK `user_id` non-nullable, ON DELETE CASCADE : la suppression d'un user
 *   purge ses logs.
 * - CHECK `xp_earned >= 0` et `gold_earned >= 0` pour verrouiller l'invariant
 *   métier côté base (le service rejette déjà les valeurs négatives).
 * - Index `(user_id, logged_at)` indispensable pour la pagination des
 *   journaux par user et pour les évaluateurs de quêtes futurs (PMVP-022).
 */
final class Version20260528200000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Post-MVP PMVP-005 : table habit_logs (trace immuable des exécutions d\'habitudes).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE habit_logs (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                habit_id INT NOT NULL,
                user_id INT NOT NULL,
                logged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                xp_earned INT NOT NULL DEFAULT 0,
                gold_earned INT NOT NULL DEFAULT 0,
                note TEXT DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE INDEX idx_habit_logs_user_logged_at ON habit_logs (user_id, logged_at)');
        $this->addSql('CREATE INDEX idx_habit_logs_habit ON habit_logs (habit_id)');

        $this->addSql(<<<'SQL'
            ALTER TABLE habit_logs
            ADD CONSTRAINT fk_habit_logs_habit
            FOREIGN KEY (habit_id)
            REFERENCES habits (id)
            ON DELETE CASCADE
            NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE habit_logs
            ADD CONSTRAINT fk_habit_logs_user
            FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
            NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE habit_logs
            ADD CONSTRAINT chk_habit_logs_xp_earned_non_negative
            CHECK (xp_earned >= 0)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE habit_logs
            ADD CONSTRAINT chk_habit_logs_gold_earned_non_negative
            CHECK (gold_earned >= 0)
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS habit_logs');
    }
}
