<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Post-MVP PMVP-017 + PMVP-018 — achievements et streaks utilisateur.
 */
final class Version20260528240000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Post-MVP PMVP-017/018 : tables achievements, user_achievements, colonnes streak sur users.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE achievements (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                code VARCHAR(50) NOT NULL,
                name VARCHAR(120) NOT NULL,
                description TEXT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_achievements_code ON achievements (code)');

        $this->addSql(<<<'SQL'
            CREATE TABLE user_achievements (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                achievement_id INT NOT NULL,
                unlocked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_user_achievements_user_achievement ON user_achievements (user_id, achievement_id)');
        $this->addSql('CREATE INDEX idx_user_achievements_user ON user_achievements (user_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE user_achievements
            ADD CONSTRAINT fk_user_achievements_user
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_achievements
            ADD CONSTRAINT fk_user_achievements_achievement
            FOREIGN KEY (achievement_id) REFERENCES achievements (id) ON DELETE CASCADE
        SQL);

        $this->addSql('ALTER TABLE users ADD current_streak INT NOT NULL DEFAULT 0');
        $this->addSql('ALTER TABLE users ADD longest_streak INT NOT NULL DEFAULT 0');
        $this->addSql('ALTER TABLE users ADD last_streak_date VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT chk_users_current_streak_non_negative CHECK (current_streak >= 0)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT chk_users_longest_streak_non_negative CHECK (longest_streak >= 0)');

        $this->addSql(<<<'SQL'
            INSERT INTO achievements (code, name, description) VALUES
            ('first_habit_log', 'Premier Pas', 'Enregistrer votre première exécution d''habitude.'),
            ('first_monster_kill', 'Tueur de Monstre', 'Vaincre votre premier monstre.'),
            ('iron_discipline', 'Discipline de Fer', 'Enregistrer 7 exécutions sur la même habitude.')
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_longest_streak_non_negative');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_current_streak_non_negative');
        $this->addSql('ALTER TABLE users DROP last_streak_date');
        $this->addSql('ALTER TABLE users DROP longest_streak');
        $this->addSql('ALTER TABLE users DROP current_streak');
        $this->addSql('DROP TABLE IF EXISTS user_achievements');
        $this->addSql('DROP TABLE IF EXISTS achievements');
    }
}
